stages:
  load_data:
    cmd: python ${data.syspath}src\data_load.py ${data.filepath} ${data.processed}train_test_data.csv
    deps:
      - ${data.syspath}src\data_load.py
      - ${data.filepath}
    outs:
      - ${data.processed}train_test_data.csv

  preprocess:
    cmd: python ${data.syspath}src\preprocess.py ${data.processed}train_test_data.csv ${data.syspath}src\params.yaml ${data.processed}X_train.csv ${data.processed}X_test.csv ${data.processed}y_train.csv ${data.processed}y_test.csv
    deps:
      - ${data.syspath}src\preprocess.py
      - ${data.processed}train_test_data.csv
      - ${data.syspath}src\params.yaml
    outs:
      - ${data.processed}X_train.csv
      - ${data.processed}X_test.csv
      - ${data.processed}y_train.csv
      - ${data.processed}y_test.csv

  train_logistic:
    cmd: python ${data.syspath}src\train.py ${data.syspath}src\params.yaml ${data.processed}X_train.csv ${data.processed}y_train.csv lr
    deps:
      - ${data.syspath}src\train.py
      - ${data.processed}X_train.csv
      - ${data.processed}y_train.csv
      - ${data.syspath}src\params.yaml
      
    outs:
      - ${data.models}lr_model.pkl

  train_clf:
    cmd: python ${data.syspath}\src\train.py ${data.syspath}src\params.yaml ${data.processed}X_train.csv ${data.processed}y_train.csv clf
    deps:
      - ${data.syspath}src\train.py
      - ${data.processed}X_train.csv
      - ${data.processed}y_train.csv
      - ${data.syspath}src\params.yaml
      
    outs:
      - ${data.models}clf_model.pkl

  train_xgb:
    cmd: python ${data.syspath}src\train.py ${data.syspath}src\params.yaml ${data.processed}X_train.csv ${data.processed}y_train.csv xgb
    deps:
      - ${data.syspath}src\train.py
      - ${data.processed}X_train.csv
      - ${data.processed}y_train.csv
      - ${data.syspath}src\params.yaml
      
    outs:
      - ${data.models}xgb_model.pkl


  evaluate_lr:
    cmd: python ${data.syspath}src\evaluate.py ${data.models}lr_model.pkl ${data.processed}X_test.csv ${data.processed}y_test.csv ${data.reports}lr_evaluation.txt
    deps:
      - ${data.syspath}src\evaluate.py
      - ${data.models}lr_model.pkl
      - ${data.processed}X_test.csv
      - ${data.processed}y_test.csv
    outs:
      - ${data.reports}lr_evaluation.txt


  evaluate_clf:
    cmd: python ${data.syspath}src\evaluate.py ${data.models}clf_model.pkl ${data.processed}X_test.csv ${data.processed}y_test.csv ${data.reports}clf_evaluation.txt
    deps:
      - ${data.syspath}src\evaluate.py
      - ${data.models}clf_model.pkl
      - ${data.processed}X_test.csv
      - ${data.processed}y_test.csv
    outs:
      - ${data.reports}clf_evaluation.txt
  
  evaluate_xgb:
    cmd: python ${data.syspath}src\evaluate.py ${data.models}xgb_model.pkl ${data.processed}X_test.csv ${data.processed}y_test.csv ${data.reports}xgb_evaluation.txt
    deps:
      - ${data.syspath}src\evaluate.py
      - ${data.models}xgb_model.pkl
      - ${data.processed}X_test.csv
      - ${data.processed}y_test.csv
    outs:
      - ${data.reports}xgb_evaluation.txt