data:
  srcpath: C:\Users\Comunicaciones 6\Documents\Andru\Eq_34\MNA-MLOps-\MNA_MLOps_Eq34\src\
  filepath: C:\Users\Comunicaciones 6\Documents\Andru\Eq_34\MNA-MLOps-\MNA_MLOps_Eq34\data\raw\
  processed: C:\Users\Comunicaciones 6\Documents\Andru\Eq_34\MNA-MLOps-\MNA_MLOps_Eq34\data\processed\
  models: C:\Users\Comunicaciones 6\Documents\Andru\Eq_34\MNA-MLOps-\MNA_MLOps_Eq34\models\
  reports: C:\Users\Comunicaciones 6\Documents\Andru\Eq_34\MNA-MLOps-\MNA_MLOps_Eq34\reports\
  plots: C:\Users\Comunicaciones 6\Documents\Andru\Eq_34\MNA-MLOps-\MNA_MLOps_Eq34\dvclive\plots\
  metrics: C:\Users\Comunicaciones 6\Documents\Andru\Eq_34\MNA-MLOps-\MNA_MLOps_Eq34\metrics\